✨[FEAT] #1 - 스튜디오맵 뷰 구현하기
TeamFILL-IN/Fill-iOS pull request #5
Opened 2022-01-09 23:08 UTC by jumining

## 🐯 PR 요약

🌱 작업한 브랜치
- feature/#1

🌱 작업한 내용
- 네이버 지도 야간모드로 구현
- 현재 나의 위치를 나타내주는 버튼 구현
- 핀 임시로 표시해보기 (버튼 눌렀을 때의 상태변화는 지금 구현X)
- 검색 창 구현
+) 검색 창 구현에서 안에 텍스트의 폰트 적용이 안되는 문제 발생했습니당...ㅜㅅㅠ 

## 📸 스크린샷

|기능|스크린샷|기능|스크린샷|
|:--:|:--:|:--:|:--:|
|전체화면|
<img src="https://user-images.githubusercontent.com/76610340/148704497-f59f90c4-2e88-4b07-ae60-3ea3320c6c1c.PNG" width="150">
|GIF|
<img src="https://user-images.githubusercontent.com/76610340/148704872-13e7fd9b-9900-4d58-b40b-252b2906e0c4.gif" width="150"
|

## 📮 관련 이슈
- Resolved: #1

2022-01-10 08:15 UTC, 66jxndoe commented
우와 멋지네요!

2022-01-10 09:39 UTC, dlwns33 requested changes
주미니 수고했어~ 코리만 반영해주고 푸시한번 더해주면 바로 볼게 !

2022-01-10 09:39 UTC, dlwns33 commented on Fillin-iOS/Fillin-iOS.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = 3FAK98S72C;
아 미친 생각해보니까 나중에 릴리즈 하려면 이것도 우리 통일해야되는데...  우리 합숙할때 내가 이거 맞춰줄게 일단은 계속 이렇게 바꾸자...

2022-01-10 09:39 UTC, dlwns33 commented on Fillin-iOS/Fillin-iOS/Sources/ViewControllers/StudioMapViewController/StudioMapViewController.swift
> +    $0.textColor = .grey2 // 검색했을 때 글씨색 질문
만약에 이 코드에서 무슨 할일이 있으면 !
`// TODO:`
이렇게 시작하면 SwiftLint가 알아서 노란색 Warning으로 잡아줘서 나중에 다시 보기 편해!

2022-01-10 09:39 UTC, dlwns33 commented on Fillin-iOS/Fillin-iOS/Sources/ViewControllers/StudioMapViewController/StudioMapViewController.swift
> +    $0.font = UIFont(name: "NotoSansKR-Regular", size: 14)
폰트는 내가 extension에 넣어놔서 제플린 보고 
![image](https://user-images.githubusercontent.com/69078056/148742288-00142d74-cbf7-4ae2-a464-9ca9d4e86043.png)
여기 typeface에 나오는걸로 맞춰주세요~
 `       label.font = .headline`
요런식으로!


내가 info.plist에 폰트 추가하는걸 깜빡해서 바로 해서 풀리퀘 올릴테니 그거 풀 받아서 사용하면 되요!

2022-01-10 09:39 UTC, dlwns33 commented on Fillin-iOS/Fillin-iOS/Sources/ViewControllers/StudioMapViewController/StudioMapViewController.swift
> +      $0.bottom.equalTo(self.view.snp.bottom)
보통 constraint 써주는 순서가 top, leading, bottom, trailing 이렇게 된대
시계 반대방향..!

2022-01-10 09:39 UTC, dlwns33 commented on Fillin-iOS/Fillin-iOS/Sources/ViewControllers/StudioMapViewController/StudioMapViewController.swift
> +    marker.iconImage = NMFOverlayImage(name: "icnPlaceBig")
이거 이미지 이름 직접 써주지 말고 Gen으로 관리하는 Assets.iconPlaceBig으로 바꿔주세요~

2022-01-10 09:39 UTC, dlwns33 commented on Fillin-iOS/Fillin-iOS/Sources/ViewControllers/StudioMapViewController/StudioMapViewController.swift
> +    myLocationButton.setImage(UIImage(named: "icnMyLocation"), for: .normal)
이거 이미지 이름 직접 써주지 말고 Gen으로 관리하는 Assets.iconMyLocation으로 바꿔주세요~

2022-01-10 09:39 UTC, dlwns33 commented on Fillin-iOS/Fillin-iOS/Sources/ViewControllers/StudioMapViewController/StudioMapViewController.swift
> +}
Action관련 함수는 코드컨벤션 따라서 동사원형 + 목적어 ex) touchBackButton로 수정해주세요~

2022-01-10 09:39 UTC, dlwns33 commented on Fillin-iOS/Fillin-iOS/Sources/ViewControllers/StudioMapViewController/StudioMapViewController.swift
> +  }
이거 isSelected를 반대로 만들어 주고 싶은거 맞나? 그렇다면 분기처리 대신
`sender.isSelected = !sender.isSelected`
요거 한줄만 써주면 돼요!

2022-01-10 09:39 UTC, dlwns33 commented on Fillin-iOS/Fillin-iOS/Sources/ViewControllers/StudioMapViewController/StudioMapViewController.swift
> +      $0.bottom.equalTo(self.view).inset(48)
오토레이아웃 잡을때 4군데 다 잡아주는거 대신 위.아래 중에 하나 택해서 잡고, leading/trailing 중에 하나 택해서 잡으면 코드가 조금 더 간결해질거같아!

 그리구 left/right 보다는 leading/trailing으로 쓰는걸 권장한대!

2022-01-11 02:16 UTC, l2hyunwoo commented on Fillin-iOS/Fillin-iOS/Sources/ViewControllers/StudioMapViewController/StudioMapViewController.swift
> +  }
안녕하세요, 질문이 있어서 리뷰에 남깁니다! 이 부분이 지금 누르면 현 위치로 카메라 포지션 + 위치를 움직여야하는데 LocationButtonView 내부 구현된걸 보니까 이미지 커스텀이 힘들어서 안드로이드는 아마 그대로 갈 것 같은데 iOS는 어떻게 대응하고 있는 지 알 수 있을까요? iOS NaverMap SDK도 확인해보니까 그런 View customization 하는 기능은 지원되지 않는 것 같아서요

2022-01-11 02:17 UTC, l2hyunwoo commented on Fillin-iOS/Fillin-iOS/Sources/ViewControllers/StudioMapViewController/StudioMapViewController.swift
> +  }
[사용자 상호작용 관련 문서](https://navermaps.github.io/ios-map-sdk/guide-ko/4-1.html)

2022-01-11 03:49 UTC, dlwns33 approved these changes
주민이 수고했어요~🦦

2022-01-11 03:49 UTC, dlwns33 commented on Fillin-iOS/Fillin-iOS/Sources/ViewControllers/StudioMapViewController/StudioMapViewController.swift
> +      NSAttributedString.Key.font: UIFont(name: "NotoSansKR-Regular", size: 14)!
주민아 요기 폰트 constant에 있는 폰트로 바꺼주세요!

2022-01-12 08:01 UTC, merged

2022-01-12 15:36 UTC, jumining commented on Fillin-iOS/Fillin-iOS/Sources/ViewControllers/StudioMapViewController/StudioMapViewController.swift
> +  }
원래의 현재 위치를 나타내는 기본제공 버튼은 비활성화 처리해줘서 삭제했고, 버튼을 따로 추가해서 커스텀 이미지 넣어주고 버튼 눌렀을 때의 액션을 함수로 따로 처리해주었습니다. 그 함수에서 위치 추적 모드를 코드로 간단하게 설정만 해주면 돼서 설정해주었어요!

2022-01-13 07:41 UTC, Kim-jisoo11 reviewed
츄미니 쵝오!